/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.analysis;

import java.util.*;
import net.sf.jame.contextfree.cfdg.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    public void caseACfdg(ACfdg node)
    {
        defaultCase(node);
    }

    public void caseARuleFigureDeclaration(ARuleFigureDeclaration node)
    {
        defaultCase(node);
    }

    public void caseAPathFigureDeclaration(APathFigureDeclaration node)
    {
        defaultCase(node);
    }

    public void caseAStartshapeDeclaration(AStartshapeDeclaration node)
    {
        defaultCase(node);
    }

    public void caseAIncludeDeclaration(AIncludeDeclaration node)
    {
        defaultCase(node);
    }

    public void caseABackgroundDeclaration(ABackgroundDeclaration node)
    {
        defaultCase(node);
    }

    public void caseADefaultTileDeclaration(ADefaultTileDeclaration node)
    {
        defaultCase(node);
    }

    public void caseAOrderedTileDeclaration(AOrderedTileDeclaration node)
    {
        defaultCase(node);
    }

    public void caseADefaultSizeDeclaration(ADefaultSizeDeclaration node)
    {
        defaultCase(node);
    }

    public void caseAOrderedSizeDeclaration(AOrderedSizeDeclaration node)
    {
        defaultCase(node);
    }

    public void caseARuleDeclaration(ARuleDeclaration node)
    {
        defaultCase(node);
    }

    public void caseAShapeDeclaration(AShapeDeclaration node)
    {
        defaultCase(node);
    }

    public void caseAPathDeclaration(APathDeclaration node)
    {
        defaultCase(node);
    }

    public void caseALoopShapeReplacementDeclaration(ALoopShapeReplacementDeclaration node)
    {
        defaultCase(node);
    }

    public void caseAShapeShapeReplacementDeclaration(AShapeShapeReplacementDeclaration node)
    {
        defaultCase(node);
    }

    public void caseADefaultShapeReplacement(ADefaultShapeReplacement node)
    {
        defaultCase(node);
    }

    public void caseAOrderedShapeReplacement(AOrderedShapeReplacement node)
    {
        defaultCase(node);
    }

    public void caseAListShapeReplacement(AListShapeReplacement node)
    {
        defaultCase(node);
    }

    public void caseALoopShapeReplacement(ALoopShapeReplacement node)
    {
        defaultCase(node);
    }

    public void caseAShapeLoopShapeReplacementBody(AShapeLoopShapeReplacementBody node)
    {
        defaultCase(node);
    }

    public void caseAListLoopShapeReplacementBody(AListLoopShapeReplacementBody node)
    {
        defaultCase(node);
    }

    public void caseAStarOperator(AStarOperator node)
    {
        defaultCase(node);
    }

    public void caseAPlusOperator(APlusOperator node)
    {
        defaultCase(node);
    }

    public void caseAMinusOperator(AMinusOperator node)
    {
        defaultCase(node);
    }

    public void caseASlashOperator(ASlashOperator node)
    {
        defaultCase(node);
    }

    public void caseAArrowOperator(AArrowOperator node)
    {
        defaultCase(node);
    }

    public void caseALoopPathOperationDeclaration(ALoopPathOperationDeclaration node)
    {
        defaultCase(node);
    }

    public void caseAPathPathOperationDeclaration(APathPathOperationDeclaration node)
    {
        defaultCase(node);
    }

    public void caseADefaultSimplePathOperation(ADefaultSimplePathOperation node)
    {
        defaultCase(node);
    }

    public void caseAOrderedSimplePathOperation(AOrderedSimplePathOperation node)
    {
        defaultCase(node);
    }

    public void caseADefaultPathopPathOperation(ADefaultPathopPathOperation node)
    {
        defaultCase(node);
    }

    public void caseAOrderedPathopPathOperation(AOrderedPathopPathOperation node)
    {
        defaultCase(node);
    }

    public void caseASimplePathOperation(ASimplePathOperation node)
    {
        defaultCase(node);
    }

    public void caseAPathopPathOperation(APathopPathOperation node)
    {
        defaultCase(node);
    }

    public void caseAListPathOperation(AListPathOperation node)
    {
        defaultCase(node);
    }

    public void caseALoopPathOperation(ALoopPathOperation node)
    {
        defaultCase(node);
    }

    public void caseAPathLoopPathOperationBody(APathLoopPathOperationBody node)
    {
        defaultCase(node);
    }

    public void caseAListLoopPathOperationBody(AListLoopPathOperationBody node)
    {
        defaultCase(node);
    }

    public void caseAXPathPoints(AXPathPoints node)
    {
        defaultCase(node);
    }

    public void caseAYPathPoints(AYPathPoints node)
    {
        defaultCase(node);
    }

    public void caseAX1PathPoints(AX1PathPoints node)
    {
        defaultCase(node);
    }

    public void caseAY1PathPoints(AY1PathPoints node)
    {
        defaultCase(node);
    }

    public void caseAX2PathPoints(AX2PathPoints node)
    {
        defaultCase(node);
    }

    public void caseAY2PathPoints(AY2PathPoints node)
    {
        defaultCase(node);
    }

    public void caseARxPathPoints(ARxPathPoints node)
    {
        defaultCase(node);
    }

    public void caseARyPathPoints(ARyPathPoints node)
    {
        defaultCase(node);
    }

    public void caseARotatePathPoints(ARotatePathPoints node)
    {
        defaultCase(node);
    }

    public void caseAParametersPathPoints(AParametersPathPoints node)
    {
        defaultCase(node);
    }

    public void caseAColorPathAdjustment(AColorPathAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAGeometryPathAdjustment(AGeometryPathAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAStrokePathAdjustment(AStrokePathAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAParametersPathAdjustment(AParametersPathAdjustment node)
    {
        defaultCase(node);
    }

    public void caseABackgroundAdjustment(ABackgroundAdjustment node)
    {
        defaultCase(node);
    }

    public void caseATileAdjustment(ATileAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAXSizeAdjustment(AXSizeAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAYSizeAdjustment(AYSizeAdjustment node)
    {
        defaultCase(node);
    }

    public void caseASizeSizeAdjustment(ASizeSizeAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAColorShapeAdjustment(AColorShapeAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAGeometryShapeAdjustment(AGeometryShapeAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAZShapeAdjustment(AZShapeAdjustment node)
    {
        defaultCase(node);
    }

    public void caseASize3ShapeAdjustment(ASize3ShapeAdjustment node)
    {
        defaultCase(node);
    }

    public void caseASimpleColorAdjustment(ASimpleColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseATargetColorAdjustment(ATargetColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAHueSimpleColorAdjustment(AHueSimpleColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseABrightnessSimpleColorAdjustment(ABrightnessSimpleColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseASaturationSimpleColorAdjustment(ASaturationSimpleColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAAlphaSimpleColorAdjustment(AAlphaSimpleColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAHueTargetColorAdjustment(AHueTargetColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseABrightnessTargetColorAdjustment(ABrightnessTargetColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseASaturationTargetColorAdjustment(ASaturationTargetColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAAlphaTargetColorAdjustment(AAlphaTargetColorAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAXGeometryAdjustment(AXGeometryAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAYGeometryAdjustment(AYGeometryAdjustment node)
    {
        defaultCase(node);
    }

    public void caseASizeGeometryAdjustment(ASizeGeometryAdjustment node)
    {
        defaultCase(node);
    }

    public void caseASize2GeometryAdjustment(ASize2GeometryAdjustment node)
    {
        defaultCase(node);
    }

    public void caseAFlipGeometryAdjustment(AFlipGeometryAdjustment node)
    {
        defaultCase(node);
    }

    public void caseASkewGeometryAdjustment(ASkewGeometryAdjustment node)
    {
        defaultCase(node);
    }

    public void caseARotateGeometryAdjustment(ARotateGeometryAdjustment node)
    {
        defaultCase(node);
    }

    public void caseANumberExpression(ANumberExpression node)
    {
        defaultCase(node);
    }

    public void caseANestedExpression(ANestedExpression node)
    {
        defaultCase(node);
    }

    public void caseAFunctionExpression(AFunctionExpression node)
    {
        defaultCase(node);
    }

    public void caseANumberExpression2(ANumberExpression2 node)
    {
        defaultCase(node);
    }

    public void caseAFunctionExpression2(AFunctionExpression2 node)
    {
        defaultCase(node);
    }

    public void caseANestedExpression2(ANestedExpression2 node)
    {
        defaultCase(node);
    }

    public void caseAComposedExpression2(AComposedExpression2 node)
    {
        defaultCase(node);
    }

    public void caseAArg0Function(AArg0Function node)
    {
        defaultCase(node);
    }

    public void caseAArg1Function(AArg1Function node)
    {
        defaultCase(node);
    }

    public void caseAArg2Function(AArg2Function node)
    {
        defaultCase(node);
    }

    public void caseAFirstExpression(AFirstExpression node)
    {
        defaultCase(node);
    }

    public void caseASecondExpression(ASecondExpression node)
    {
        defaultCase(node);
    }

    public void caseAThirdExpression(AThirdExpression node)
    {
        defaultCase(node);
    }

    public void caseTBar(TBar node)
    {
        defaultCase(node);
    }

    public void caseTStar(TStar node)
    {
        defaultCase(node);
    }

    public void caseTPlus(TPlus node)
    {
        defaultCase(node);
    }

    public void caseTMinus(TMinus node)
    {
        defaultCase(node);
    }

    public void caseTSlash(TSlash node)
    {
        defaultCase(node);
    }

    public void caseTArrow(TArrow node)
    {
        defaultCase(node);
    }

    public void caseTComma(TComma node)
    {
        defaultCase(node);
    }

    public void caseTLCbkt(TLCbkt node)
    {
        defaultCase(node);
    }

    public void caseTRCbkt(TRCbkt node)
    {
        defaultCase(node);
    }

    public void caseTLRbkt(TLRbkt node)
    {
        defaultCase(node);
    }

    public void caseTRRbkt(TRRbkt node)
    {
        defaultCase(node);
    }

    public void caseTLSbkt(TLSbkt node)
    {
        defaultCase(node);
    }

    public void caseTRSbkt(TRSbkt node)
    {
        defaultCase(node);
    }

    public void caseTStartshape(TStartshape node)
    {
        defaultCase(node);
    }

    public void caseTBackground(TBackground node)
    {
        defaultCase(node);
    }

    public void caseTInclude(TInclude node)
    {
        defaultCase(node);
    }

    public void caseTTile(TTile node)
    {
        defaultCase(node);
    }

    public void caseTSize(TSize node)
    {
        defaultCase(node);
    }

    public void caseTRule(TRule node)
    {
        defaultCase(node);
    }

    public void caseTPath(TPath node)
    {
        defaultCase(node);
    }

    public void caseTShape(TShape node)
    {
        defaultCase(node);
    }

    public void caseTParametersToken(TParametersToken node)
    {
        defaultCase(node);
    }

    public void caseTSizeToken(TSizeToken node)
    {
        defaultCase(node);
    }

    public void caseTHueToken(THueToken node)
    {
        defaultCase(node);
    }

    public void caseTSaturationToken(TSaturationToken node)
    {
        defaultCase(node);
    }

    public void caseTBrightnessToken(TBrightnessToken node)
    {
        defaultCase(node);
    }

    public void caseTAlphaToken(TAlphaToken node)
    {
        defaultCase(node);
    }

    public void caseTTargetHueToken(TTargetHueToken node)
    {
        defaultCase(node);
    }

    public void caseTTargetSaturationToken(TTargetSaturationToken node)
    {
        defaultCase(node);
    }

    public void caseTTargetBrightnessToken(TTargetBrightnessToken node)
    {
        defaultCase(node);
    }

    public void caseTTargetAlphaToken(TTargetAlphaToken node)
    {
        defaultCase(node);
    }

    public void caseTXToken(TXToken node)
    {
        defaultCase(node);
    }

    public void caseTYToken(TYToken node)
    {
        defaultCase(node);
    }

    public void caseTZToken(TZToken node)
    {
        defaultCase(node);
    }

    public void caseTX1Token(TX1Token node)
    {
        defaultCase(node);
    }

    public void caseTY1Token(TY1Token node)
    {
        defaultCase(node);
    }

    public void caseTX2Token(TX2Token node)
    {
        defaultCase(node);
    }

    public void caseTY2Token(TY2Token node)
    {
        defaultCase(node);
    }

    public void caseTRxToken(TRxToken node)
    {
        defaultCase(node);
    }

    public void caseTRyToken(TRyToken node)
    {
        defaultCase(node);
    }

    public void caseTRotateToken(TRotateToken node)
    {
        defaultCase(node);
    }

    public void caseTFlipToken(TFlipToken node)
    {
        defaultCase(node);
    }

    public void caseTSkewToken(TSkewToken node)
    {
        defaultCase(node);
    }

    public void caseTStrokewidthToken(TStrokewidthToken node)
    {
        defaultCase(node);
    }

    public void caseTPathop(TPathop node)
    {
        defaultCase(node);
    }

    public void caseTFilename(TFilename node)
    {
        defaultCase(node);
    }

    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    public void caseTNumber(TNumber node)
    {
        defaultCase(node);
    }

    public void caseTWhiteSpace(TWhiteSpace node)
    {
        defaultCase(node);
    }

    public void caseTLineComment(TLineComment node)
    {
        defaultCase(node);
    }

    public void caseTBlockComment(TBlockComment node)
    {
        defaultCase(node);
    }

    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
