/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.analysis;

import java.util.*;
import net.sf.jame.contextfree.cfdg.node.*;

public class DepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getPCfdg().apply(this);
        node.getEOF().apply(this);
        outStart(node);
    }

    public void inACfdg(ACfdg node)
    {
        defaultIn(node);
    }

    public void outACfdg(ACfdg node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACfdg(ACfdg node)
    {
        inACfdg(node);
        {
            List<PStartshapeDeclaration> copy = new ArrayList<PStartshapeDeclaration>(node.getStartshapeDeclaration());
            for(PStartshapeDeclaration e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PIncludeDeclaration> copy = new ArrayList<PIncludeDeclaration>(node.getIncludeDeclaration());
            for(PIncludeDeclaration e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getBackgroundDeclaration() != null)
        {
            node.getBackgroundDeclaration().apply(this);
        }
        if(node.getTileDeclaration() != null)
        {
            node.getTileDeclaration().apply(this);
        }
        if(node.getSizeDeclaration() != null)
        {
            node.getSizeDeclaration().apply(this);
        }
        {
            List<PFigureDeclaration> copy = new ArrayList<PFigureDeclaration>(node.getFigureDeclaration());
            for(PFigureDeclaration e : copy)
            {
                e.apply(this);
            }
        }
        outACfdg(node);
    }

    public void inARuleFigureDeclaration(ARuleFigureDeclaration node)
    {
        defaultIn(node);
    }

    public void outARuleFigureDeclaration(ARuleFigureDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARuleFigureDeclaration(ARuleFigureDeclaration node)
    {
        inARuleFigureDeclaration(node);
        if(node.getRuleDeclaration() != null)
        {
            node.getRuleDeclaration().apply(this);
        }
        outARuleFigureDeclaration(node);
    }

    public void inAPathFigureDeclaration(APathFigureDeclaration node)
    {
        defaultIn(node);
    }

    public void outAPathFigureDeclaration(APathFigureDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPathFigureDeclaration(APathFigureDeclaration node)
    {
        inAPathFigureDeclaration(node);
        if(node.getPathDeclaration() != null)
        {
            node.getPathDeclaration().apply(this);
        }
        outAPathFigureDeclaration(node);
    }

    public void inAStartshapeDeclaration(AStartshapeDeclaration node)
    {
        defaultIn(node);
    }

    public void outAStartshapeDeclaration(AStartshapeDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStartshapeDeclaration(AStartshapeDeclaration node)
    {
        inAStartshapeDeclaration(node);
        if(node.getStartshape() != null)
        {
            node.getStartshape().apply(this);
        }
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStartshapeDeclaration(node);
    }

    public void inAIncludeDeclaration(AIncludeDeclaration node)
    {
        defaultIn(node);
    }

    public void outAIncludeDeclaration(AIncludeDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIncludeDeclaration(AIncludeDeclaration node)
    {
        inAIncludeDeclaration(node);
        if(node.getInclude() != null)
        {
            node.getInclude().apply(this);
        }
        if(node.getFilename() != null)
        {
            node.getFilename().apply(this);
        }
        outAIncludeDeclaration(node);
    }

    public void inABackgroundDeclaration(ABackgroundDeclaration node)
    {
        defaultIn(node);
    }

    public void outABackgroundDeclaration(ABackgroundDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABackgroundDeclaration(ABackgroundDeclaration node)
    {
        inABackgroundDeclaration(node);
        if(node.getBackground() != null)
        {
            node.getBackground().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PBackgroundAdjustment> copy = new ArrayList<PBackgroundAdjustment>(node.getBackgroundAdjustment());
            for(PBackgroundAdjustment e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outABackgroundDeclaration(node);
    }

    public void inATileDeclaration(ATileDeclaration node)
    {
        defaultIn(node);
    }

    public void outATileDeclaration(ATileDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATileDeclaration(ATileDeclaration node)
    {
        inATileDeclaration(node);
        if(node.getTile() != null)
        {
            node.getTile().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PTileAdjustment> copy = new ArrayList<PTileAdjustment>(node.getTileAdjustment());
            for(PTileAdjustment e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outATileDeclaration(node);
    }

    public void inASizeDeclaration(ASizeDeclaration node)
    {
        defaultIn(node);
    }

    public void outASizeDeclaration(ASizeDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASizeDeclaration(ASizeDeclaration node)
    {
        inASizeDeclaration(node);
        if(node.getSize() != null)
        {
            node.getSize().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PSizeAdjustment> copy = new ArrayList<PSizeAdjustment>(node.getSizeAdjustment());
            for(PSizeAdjustment e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outASizeDeclaration(node);
    }

    public void inARuleDeclaration(ARuleDeclaration node)
    {
        defaultIn(node);
    }

    public void outARuleDeclaration(ARuleDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARuleDeclaration(ARuleDeclaration node)
    {
        inARuleDeclaration(node);
        if(node.getRule() != null)
        {
            node.getRule().apply(this);
        }
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PShapeReplacementDeclaration> copy = new ArrayList<PShapeReplacementDeclaration>(node.getShapeReplacementDeclaration());
            for(PShapeReplacementDeclaration e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outARuleDeclaration(node);
    }

    public void inAMultiShapeReplacementDeclaration(AMultiShapeReplacementDeclaration node)
    {
        defaultIn(node);
    }

    public void outAMultiShapeReplacementDeclaration(AMultiShapeReplacementDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiShapeReplacementDeclaration(AMultiShapeReplacementDeclaration node)
    {
        inAMultiShapeReplacementDeclaration(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        if(node.getStar() != null)
        {
            node.getStar().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PShapeAdjustment> copy = new ArrayList<PShapeAdjustment>(node.getShapeAdjustment());
            for(PShapeAdjustment e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        if(node.getShapeReplacementBlock() != null)
        {
            node.getShapeReplacementBlock().apply(this);
        }
        outAMultiShapeReplacementDeclaration(node);
    }

    public void inASingleShapeReplacementDeclaration(ASingleShapeReplacementDeclaration node)
    {
        defaultIn(node);
    }

    public void outASingleShapeReplacementDeclaration(ASingleShapeReplacementDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASingleShapeReplacementDeclaration(ASingleShapeReplacementDeclaration node)
    {
        inASingleShapeReplacementDeclaration(node);
        if(node.getShapeReplacement() != null)
        {
            node.getShapeReplacement().apply(this);
        }
        outASingleShapeReplacementDeclaration(node);
    }

    public void inABasicShapeReplacement(ABasicShapeReplacement node)
    {
        defaultIn(node);
    }

    public void outABasicShapeReplacement(ABasicShapeReplacement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABasicShapeReplacement(ABasicShapeReplacement node)
    {
        inABasicShapeReplacement(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PShapeAdjustment> copy = new ArrayList<PShapeAdjustment>(node.getShapeAdjustment());
            for(PShapeAdjustment e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outABasicShapeReplacement(node);
    }

    public void inAOrderedShapeReplacement(AOrderedShapeReplacement node)
    {
        defaultIn(node);
    }

    public void outAOrderedShapeReplacement(AOrderedShapeReplacement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrderedShapeReplacement(AOrderedShapeReplacement node)
    {
        inAOrderedShapeReplacement(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        if(node.getLSbkt() != null)
        {
            node.getLSbkt().apply(this);
        }
        {
            List<PShapeAdjustment> copy = new ArrayList<PShapeAdjustment>(node.getShapeAdjustment());
            for(PShapeAdjustment e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRSbkt() != null)
        {
            node.getRSbkt().apply(this);
        }
        outAOrderedShapeReplacement(node);
    }

    public void inABasicShapeReplacementBlock(ABasicShapeReplacementBlock node)
    {
        defaultIn(node);
    }

    public void outABasicShapeReplacementBlock(ABasicShapeReplacementBlock node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABasicShapeReplacementBlock(ABasicShapeReplacementBlock node)
    {
        inABasicShapeReplacementBlock(node);
        if(node.getShapeReplacement() != null)
        {
            node.getShapeReplacement().apply(this);
        }
        outABasicShapeReplacementBlock(node);
    }

    public void inAListShapeReplacementBlock(AListShapeReplacementBlock node)
    {
        defaultIn(node);
    }

    public void outAListShapeReplacementBlock(AListShapeReplacementBlock node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListShapeReplacementBlock(AListShapeReplacementBlock node)
    {
        inAListShapeReplacementBlock(node);
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PShapeReplacementDeclaration> copy = new ArrayList<PShapeReplacementDeclaration>(node.getShapeReplacementDeclaration());
            for(PShapeReplacementDeclaration e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outAListShapeReplacementBlock(node);
    }

    public void inAStarOperator(AStarOperator node)
    {
        defaultIn(node);
    }

    public void outAStarOperator(AStarOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStarOperator(AStarOperator node)
    {
        inAStarOperator(node);
        if(node.getStar() != null)
        {
            node.getStar().apply(this);
        }
        outAStarOperator(node);
    }

    public void inAPlusOperator(APlusOperator node)
    {
        defaultIn(node);
    }

    public void outAPlusOperator(APlusOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPlusOperator(APlusOperator node)
    {
        inAPlusOperator(node);
        if(node.getPlus() != null)
        {
            node.getPlus().apply(this);
        }
        outAPlusOperator(node);
    }

    public void inAMinusOperator(AMinusOperator node)
    {
        defaultIn(node);
    }

    public void outAMinusOperator(AMinusOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMinusOperator(AMinusOperator node)
    {
        inAMinusOperator(node);
        if(node.getMinus() != null)
        {
            node.getMinus().apply(this);
        }
        outAMinusOperator(node);
    }

    public void inASlashOperator(ASlashOperator node)
    {
        defaultIn(node);
    }

    public void outASlashOperator(ASlashOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASlashOperator(ASlashOperator node)
    {
        inASlashOperator(node);
        if(node.getSlash() != null)
        {
            node.getSlash().apply(this);
        }
        outASlashOperator(node);
    }

    public void inAArrowOperator(AArrowOperator node)
    {
        defaultIn(node);
    }

    public void outAArrowOperator(AArrowOperator node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArrowOperator(AArrowOperator node)
    {
        inAArrowOperator(node);
        if(node.getArrow() != null)
        {
            node.getArrow().apply(this);
        }
        outAArrowOperator(node);
    }

    public void inAPathOperation(APathOperation node)
    {
        defaultIn(node);
    }

    public void outAPathOperation(APathOperation node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPathOperation(APathOperation node)
    {
        inAPathOperation(node);
        if(node.getPathop() != null)
        {
            node.getPathop().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PPathPoints> copy = new ArrayList<PPathPoints>(node.getPathPoints());
            for(PPathPoints e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outAPathOperation(node);
    }

    public void inABasicPathCommand(ABasicPathCommand node)
    {
        defaultIn(node);
    }

    public void outABasicPathCommand(ABasicPathCommand node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABasicPathCommand(ABasicPathCommand node)
    {
        inABasicPathCommand(node);
        if(node.getPathcmd() != null)
        {
            node.getPathcmd().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PPathAdjustment> copy = new ArrayList<PPathAdjustment>(node.getPathAdjustment());
            for(PPathAdjustment e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outABasicPathCommand(node);
    }

    public void inAOrderedPathCommand(AOrderedPathCommand node)
    {
        defaultIn(node);
    }

    public void outAOrderedPathCommand(AOrderedPathCommand node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOrderedPathCommand(AOrderedPathCommand node)
    {
        inAOrderedPathCommand(node);
        if(node.getPathcmd() != null)
        {
            node.getPathcmd().apply(this);
        }
        if(node.getLSbkt() != null)
        {
            node.getLSbkt().apply(this);
        }
        {
            List<PPathAdjustment> copy = new ArrayList<PPathAdjustment>(node.getPathAdjustment());
            for(PPathAdjustment e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRSbkt() != null)
        {
            node.getRSbkt().apply(this);
        }
        outAOrderedPathCommand(node);
    }

    public void inAPathDeclaration(APathDeclaration node)
    {
        defaultIn(node);
    }

    public void outAPathDeclaration(APathDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAPathDeclaration(APathDeclaration node)
    {
        inAPathDeclaration(node);
        if(node.getPath() != null)
        {
            node.getPath().apply(this);
        }
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PPathReplacementDeclaration> copy = new ArrayList<PPathReplacementDeclaration>(node.getPathReplacementDeclaration());
            for(PPathReplacementDeclaration e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outAPathDeclaration(node);
    }

    public void inAMultiPathReplacementDeclaration(AMultiPathReplacementDeclaration node)
    {
        defaultIn(node);
    }

    public void outAMultiPathReplacementDeclaration(AMultiPathReplacementDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultiPathReplacementDeclaration(AMultiPathReplacementDeclaration node)
    {
        inAMultiPathReplacementDeclaration(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        if(node.getStar() != null)
        {
            node.getStar().apply(this);
        }
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PPathAdjustment> copy = new ArrayList<PPathAdjustment>(node.getPathAdjustment());
            for(PPathAdjustment e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        if(node.getPathReplacementBlock() != null)
        {
            node.getPathReplacementBlock().apply(this);
        }
        outAMultiPathReplacementDeclaration(node);
    }

    public void inASinglePathReplacementDeclaration(ASinglePathReplacementDeclaration node)
    {
        defaultIn(node);
    }

    public void outASinglePathReplacementDeclaration(ASinglePathReplacementDeclaration node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASinglePathReplacementDeclaration(ASinglePathReplacementDeclaration node)
    {
        inASinglePathReplacementDeclaration(node);
        if(node.getPathReplacement() != null)
        {
            node.getPathReplacement().apply(this);
        }
        outASinglePathReplacementDeclaration(node);
    }

    public void inAOperationPathReplacement(AOperationPathReplacement node)
    {
        defaultIn(node);
    }

    public void outAOperationPathReplacement(AOperationPathReplacement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOperationPathReplacement(AOperationPathReplacement node)
    {
        inAOperationPathReplacement(node);
        if(node.getPathOperation() != null)
        {
            node.getPathOperation().apply(this);
        }
        outAOperationPathReplacement(node);
    }

    public void inACommandPathReplacement(ACommandPathReplacement node)
    {
        defaultIn(node);
    }

    public void outACommandPathReplacement(ACommandPathReplacement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACommandPathReplacement(ACommandPathReplacement node)
    {
        inACommandPathReplacement(node);
        if(node.getPathCommand() != null)
        {
            node.getPathCommand().apply(this);
        }
        outACommandPathReplacement(node);
    }

    public void inABasicPathReplacementBlock(ABasicPathReplacementBlock node)
    {
        defaultIn(node);
    }

    public void outABasicPathReplacementBlock(ABasicPathReplacementBlock node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABasicPathReplacementBlock(ABasicPathReplacementBlock node)
    {
        inABasicPathReplacementBlock(node);
        if(node.getPathReplacement() != null)
        {
            node.getPathReplacement().apply(this);
        }
        outABasicPathReplacementBlock(node);
    }

    public void inAListPathReplacementBlock(AListPathReplacementBlock node)
    {
        defaultIn(node);
    }

    public void outAListPathReplacementBlock(AListPathReplacementBlock node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListPathReplacementBlock(AListPathReplacementBlock node)
    {
        inAListPathReplacementBlock(node);
        if(node.getLCbkt() != null)
        {
            node.getLCbkt().apply(this);
        }
        {
            List<PPathReplacementDeclaration> copy = new ArrayList<PPathReplacementDeclaration>(node.getPathReplacementDeclaration());
            for(PPathReplacementDeclaration e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getRCbkt() != null)
        {
            node.getRCbkt().apply(this);
        }
        outAListPathReplacementBlock(node);
    }

    public void inAXPathPoints(AXPathPoints node)
    {
        defaultIn(node);
    }

    public void outAXPathPoints(AXPathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAXPathPoints(AXPathPoints node)
    {
        inAXPathPoints(node);
        if(node.getXToken() != null)
        {
            node.getXToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAXPathPoints(node);
    }

    public void inAYPathPoints(AYPathPoints node)
    {
        defaultIn(node);
    }

    public void outAYPathPoints(AYPathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAYPathPoints(AYPathPoints node)
    {
        inAYPathPoints(node);
        if(node.getYToken() != null)
        {
            node.getYToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAYPathPoints(node);
    }

    public void inAX1PathPoints(AX1PathPoints node)
    {
        defaultIn(node);
    }

    public void outAX1PathPoints(AX1PathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAX1PathPoints(AX1PathPoints node)
    {
        inAX1PathPoints(node);
        if(node.getX1Token() != null)
        {
            node.getX1Token().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAX1PathPoints(node);
    }

    public void inAY1PathPoints(AY1PathPoints node)
    {
        defaultIn(node);
    }

    public void outAY1PathPoints(AY1PathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAY1PathPoints(AY1PathPoints node)
    {
        inAY1PathPoints(node);
        if(node.getY1Token() != null)
        {
            node.getY1Token().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAY1PathPoints(node);
    }

    public void inAX2PathPoints(AX2PathPoints node)
    {
        defaultIn(node);
    }

    public void outAX2PathPoints(AX2PathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAX2PathPoints(AX2PathPoints node)
    {
        inAX2PathPoints(node);
        if(node.getX2Token() != null)
        {
            node.getX2Token().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAX2PathPoints(node);
    }

    public void inAY2PathPoints(AY2PathPoints node)
    {
        defaultIn(node);
    }

    public void outAY2PathPoints(AY2PathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAY2PathPoints(AY2PathPoints node)
    {
        inAY2PathPoints(node);
        if(node.getY2Token() != null)
        {
            node.getY2Token().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAY2PathPoints(node);
    }

    public void inARxPathPoints(ARxPathPoints node)
    {
        defaultIn(node);
    }

    public void outARxPathPoints(ARxPathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARxPathPoints(ARxPathPoints node)
    {
        inARxPathPoints(node);
        if(node.getRxToken() != null)
        {
            node.getRxToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outARxPathPoints(node);
    }

    public void inARyPathPoints(ARyPathPoints node)
    {
        defaultIn(node);
    }

    public void outARyPathPoints(ARyPathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARyPathPoints(ARyPathPoints node)
    {
        inARyPathPoints(node);
        if(node.getRyToken() != null)
        {
            node.getRyToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outARyPathPoints(node);
    }

    public void inARotatePathPoints(ARotatePathPoints node)
    {
        defaultIn(node);
    }

    public void outARotatePathPoints(ARotatePathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARotatePathPoints(ARotatePathPoints node)
    {
        inARotatePathPoints(node);
        if(node.getRotateToken() != null)
        {
            node.getRotateToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outARotatePathPoints(node);
    }

    public void inAParametersPathPoints(AParametersPathPoints node)
    {
        defaultIn(node);
    }

    public void outAParametersPathPoints(AParametersPathPoints node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametersPathPoints(AParametersPathPoints node)
    {
        inAParametersPathPoints(node);
        if(node.getParametersToken() != null)
        {
            node.getParametersToken().apply(this);
        }
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAParametersPathPoints(node);
    }

    public void inAColorPathAdjustment(AColorPathAdjustment node)
    {
        defaultIn(node);
    }

    public void outAColorPathAdjustment(AColorPathAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAColorPathAdjustment(AColorPathAdjustment node)
    {
        inAColorPathAdjustment(node);
        if(node.getColorAdjustment() != null)
        {
            node.getColorAdjustment().apply(this);
        }
        outAColorPathAdjustment(node);
    }

    public void inAGeometryPathAdjustment(AGeometryPathAdjustment node)
    {
        defaultIn(node);
    }

    public void outAGeometryPathAdjustment(AGeometryPathAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGeometryPathAdjustment(AGeometryPathAdjustment node)
    {
        inAGeometryPathAdjustment(node);
        if(node.getGeometryAdjustment() != null)
        {
            node.getGeometryAdjustment().apply(this);
        }
        outAGeometryPathAdjustment(node);
    }

    public void inAStrokePathAdjustment(AStrokePathAdjustment node)
    {
        defaultIn(node);
    }

    public void outAStrokePathAdjustment(AStrokePathAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStrokePathAdjustment(AStrokePathAdjustment node)
    {
        inAStrokePathAdjustment(node);
        if(node.getStrokewidthToken() != null)
        {
            node.getStrokewidthToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAStrokePathAdjustment(node);
    }

    public void inAParametersPathAdjustment(AParametersPathAdjustment node)
    {
        defaultIn(node);
    }

    public void outAParametersPathAdjustment(AParametersPathAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametersPathAdjustment(AParametersPathAdjustment node)
    {
        inAParametersPathAdjustment(node);
        if(node.getParametersToken() != null)
        {
            node.getParametersToken().apply(this);
        }
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAParametersPathAdjustment(node);
    }

    public void inAHueBackgroundAdjustment(AHueBackgroundAdjustment node)
    {
        defaultIn(node);
    }

    public void outAHueBackgroundAdjustment(AHueBackgroundAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAHueBackgroundAdjustment(AHueBackgroundAdjustment node)
    {
        inAHueBackgroundAdjustment(node);
        if(node.getHueToken() != null)
        {
            node.getHueToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAHueBackgroundAdjustment(node);
    }

    public void inABrightnessBackgroundAdjustment(ABrightnessBackgroundAdjustment node)
    {
        defaultIn(node);
    }

    public void outABrightnessBackgroundAdjustment(ABrightnessBackgroundAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABrightnessBackgroundAdjustment(ABrightnessBackgroundAdjustment node)
    {
        inABrightnessBackgroundAdjustment(node);
        if(node.getBrightnessToken() != null)
        {
            node.getBrightnessToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outABrightnessBackgroundAdjustment(node);
    }

    public void inASaturationBackgroundAdjustment(ASaturationBackgroundAdjustment node)
    {
        defaultIn(node);
    }

    public void outASaturationBackgroundAdjustment(ASaturationBackgroundAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASaturationBackgroundAdjustment(ASaturationBackgroundAdjustment node)
    {
        inASaturationBackgroundAdjustment(node);
        if(node.getSaturationToken() != null)
        {
            node.getSaturationToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outASaturationBackgroundAdjustment(node);
    }

    public void inAAlphaBackgroundAdjustment(AAlphaBackgroundAdjustment node)
    {
        defaultIn(node);
    }

    public void outAAlphaBackgroundAdjustment(AAlphaBackgroundAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAlphaBackgroundAdjustment(AAlphaBackgroundAdjustment node)
    {
        inAAlphaBackgroundAdjustment(node);
        if(node.getAlphaToken() != null)
        {
            node.getAlphaToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAAlphaBackgroundAdjustment(node);
    }

    public void inATileAdjustment(ATileAdjustment node)
    {
        defaultIn(node);
    }

    public void outATileAdjustment(ATileAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATileAdjustment(ATileAdjustment node)
    {
        inATileAdjustment(node);
        if(node.getSizeToken() != null)
        {
            node.getSizeToken().apply(this);
        }
        if(node.getFirstExpression() != null)
        {
            node.getFirstExpression().apply(this);
        }
        if(node.getSecondExpression() != null)
        {
            node.getSecondExpression().apply(this);
        }
        outATileAdjustment(node);
    }

    public void inAXSizeAdjustment(AXSizeAdjustment node)
    {
        defaultIn(node);
    }

    public void outAXSizeAdjustment(AXSizeAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAXSizeAdjustment(AXSizeAdjustment node)
    {
        inAXSizeAdjustment(node);
        if(node.getXToken() != null)
        {
            node.getXToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAXSizeAdjustment(node);
    }

    public void inAYSizeAdjustment(AYSizeAdjustment node)
    {
        defaultIn(node);
    }

    public void outAYSizeAdjustment(AYSizeAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAYSizeAdjustment(AYSizeAdjustment node)
    {
        inAYSizeAdjustment(node);
        if(node.getYToken() != null)
        {
            node.getYToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAYSizeAdjustment(node);
    }

    public void inASizeSizeAdjustment(ASizeSizeAdjustment node)
    {
        defaultIn(node);
    }

    public void outASizeSizeAdjustment(ASizeSizeAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASizeSizeAdjustment(ASizeSizeAdjustment node)
    {
        inASizeSizeAdjustment(node);
        if(node.getSizeToken() != null)
        {
            node.getSizeToken().apply(this);
        }
        if(node.getFirstExpression() != null)
        {
            node.getFirstExpression().apply(this);
        }
        if(node.getSecondExpression() != null)
        {
            node.getSecondExpression().apply(this);
        }
        outASizeSizeAdjustment(node);
    }

    public void inAColorShapeAdjustment(AColorShapeAdjustment node)
    {
        defaultIn(node);
    }

    public void outAColorShapeAdjustment(AColorShapeAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAColorShapeAdjustment(AColorShapeAdjustment node)
    {
        inAColorShapeAdjustment(node);
        if(node.getColorAdjustment() != null)
        {
            node.getColorAdjustment().apply(this);
        }
        outAColorShapeAdjustment(node);
    }

    public void inAGeometryShapeAdjustment(AGeometryShapeAdjustment node)
    {
        defaultIn(node);
    }

    public void outAGeometryShapeAdjustment(AGeometryShapeAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAGeometryShapeAdjustment(AGeometryShapeAdjustment node)
    {
        inAGeometryShapeAdjustment(node);
        if(node.getGeometryAdjustment() != null)
        {
            node.getGeometryAdjustment().apply(this);
        }
        outAGeometryShapeAdjustment(node);
    }

    public void inAZShapeAdjustment(AZShapeAdjustment node)
    {
        defaultIn(node);
    }

    public void outAZShapeAdjustment(AZShapeAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAZShapeAdjustment(AZShapeAdjustment node)
    {
        inAZShapeAdjustment(node);
        if(node.getZToken() != null)
        {
            node.getZToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAZShapeAdjustment(node);
    }

    public void inASize3ShapeAdjustment(ASize3ShapeAdjustment node)
    {
        defaultIn(node);
    }

    public void outASize3ShapeAdjustment(ASize3ShapeAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASize3ShapeAdjustment(ASize3ShapeAdjustment node)
    {
        inASize3ShapeAdjustment(node);
        if(node.getSizeToken() != null)
        {
            node.getSizeToken().apply(this);
        }
        if(node.getFirstExpression() != null)
        {
            node.getFirstExpression().apply(this);
        }
        if(node.getSecondExpression() != null)
        {
            node.getSecondExpression().apply(this);
        }
        if(node.getThirdExpression() != null)
        {
            node.getThirdExpression().apply(this);
        }
        outASize3ShapeAdjustment(node);
    }

    public void inACurrentColorAdjustment(ACurrentColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outACurrentColorAdjustment(ACurrentColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACurrentColorAdjustment(ACurrentColorAdjustment node)
    {
        inACurrentColorAdjustment(node);
        if(node.getCurrentColorAdjustment() != null)
        {
            node.getCurrentColorAdjustment().apply(this);
        }
        outACurrentColorAdjustment(node);
    }

    public void inATargetColorAdjustment(ATargetColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outATargetColorAdjustment(ATargetColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATargetColorAdjustment(ATargetColorAdjustment node)
    {
        inATargetColorAdjustment(node);
        if(node.getTargetColorAdjustment() != null)
        {
            node.getTargetColorAdjustment().apply(this);
        }
        outATargetColorAdjustment(node);
    }

    public void inAHueCurrentColorAdjustment(AHueCurrentColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outAHueCurrentColorAdjustment(AHueCurrentColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAHueCurrentColorAdjustment(AHueCurrentColorAdjustment node)
    {
        inAHueCurrentColorAdjustment(node);
        if(node.getHueToken() != null)
        {
            node.getHueToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getBar() != null)
        {
            node.getBar().apply(this);
        }
        outAHueCurrentColorAdjustment(node);
    }

    public void inABrightnessCurrentColorAdjustment(ABrightnessCurrentColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outABrightnessCurrentColorAdjustment(ABrightnessCurrentColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABrightnessCurrentColorAdjustment(ABrightnessCurrentColorAdjustment node)
    {
        inABrightnessCurrentColorAdjustment(node);
        if(node.getBrightnessToken() != null)
        {
            node.getBrightnessToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getBar() != null)
        {
            node.getBar().apply(this);
        }
        outABrightnessCurrentColorAdjustment(node);
    }

    public void inASaturationCurrentColorAdjustment(ASaturationCurrentColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outASaturationCurrentColorAdjustment(ASaturationCurrentColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASaturationCurrentColorAdjustment(ASaturationCurrentColorAdjustment node)
    {
        inASaturationCurrentColorAdjustment(node);
        if(node.getSaturationToken() != null)
        {
            node.getSaturationToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getBar() != null)
        {
            node.getBar().apply(this);
        }
        outASaturationCurrentColorAdjustment(node);
    }

    public void inAAlphaCurrentColorAdjustment(AAlphaCurrentColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outAAlphaCurrentColorAdjustment(AAlphaCurrentColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAlphaCurrentColorAdjustment(AAlphaCurrentColorAdjustment node)
    {
        inAAlphaCurrentColorAdjustment(node);
        if(node.getAlphaToken() != null)
        {
            node.getAlphaToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        if(node.getBar() != null)
        {
            node.getBar().apply(this);
        }
        outAAlphaCurrentColorAdjustment(node);
    }

    public void inAHueTargetColorAdjustment(AHueTargetColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outAHueTargetColorAdjustment(AHueTargetColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAHueTargetColorAdjustment(AHueTargetColorAdjustment node)
    {
        inAHueTargetColorAdjustment(node);
        if(node.getTargetHueToken() != null)
        {
            node.getTargetHueToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAHueTargetColorAdjustment(node);
    }

    public void inABrightnessTargetColorAdjustment(ABrightnessTargetColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outABrightnessTargetColorAdjustment(ABrightnessTargetColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABrightnessTargetColorAdjustment(ABrightnessTargetColorAdjustment node)
    {
        inABrightnessTargetColorAdjustment(node);
        if(node.getTargetBrightnessToken() != null)
        {
            node.getTargetBrightnessToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outABrightnessTargetColorAdjustment(node);
    }

    public void inASaturationTargetColorAdjustment(ASaturationTargetColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outASaturationTargetColorAdjustment(ASaturationTargetColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASaturationTargetColorAdjustment(ASaturationTargetColorAdjustment node)
    {
        inASaturationTargetColorAdjustment(node);
        if(node.getTargetSaturationToken() != null)
        {
            node.getTargetSaturationToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outASaturationTargetColorAdjustment(node);
    }

    public void inAAlphaTargetColorAdjustment(AAlphaTargetColorAdjustment node)
    {
        defaultIn(node);
    }

    public void outAAlphaTargetColorAdjustment(AAlphaTargetColorAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAlphaTargetColorAdjustment(AAlphaTargetColorAdjustment node)
    {
        inAAlphaTargetColorAdjustment(node);
        if(node.getTargetAlphaToken() != null)
        {
            node.getTargetAlphaToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAAlphaTargetColorAdjustment(node);
    }

    public void inAXGeometryAdjustment(AXGeometryAdjustment node)
    {
        defaultIn(node);
    }

    public void outAXGeometryAdjustment(AXGeometryAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAXGeometryAdjustment(AXGeometryAdjustment node)
    {
        inAXGeometryAdjustment(node);
        if(node.getXToken() != null)
        {
            node.getXToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAXGeometryAdjustment(node);
    }

    public void inAYGeometryAdjustment(AYGeometryAdjustment node)
    {
        defaultIn(node);
    }

    public void outAYGeometryAdjustment(AYGeometryAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAYGeometryAdjustment(AYGeometryAdjustment node)
    {
        inAYGeometryAdjustment(node);
        if(node.getYToken() != null)
        {
            node.getYToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAYGeometryAdjustment(node);
    }

    public void inASizeGeometryAdjustment(ASizeGeometryAdjustment node)
    {
        defaultIn(node);
    }

    public void outASizeGeometryAdjustment(ASizeGeometryAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASizeGeometryAdjustment(ASizeGeometryAdjustment node)
    {
        inASizeGeometryAdjustment(node);
        if(node.getSizeToken() != null)
        {
            node.getSizeToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outASizeGeometryAdjustment(node);
    }

    public void inASize2GeometryAdjustment(ASize2GeometryAdjustment node)
    {
        defaultIn(node);
    }

    public void outASize2GeometryAdjustment(ASize2GeometryAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASize2GeometryAdjustment(ASize2GeometryAdjustment node)
    {
        inASize2GeometryAdjustment(node);
        if(node.getSizeToken() != null)
        {
            node.getSizeToken().apply(this);
        }
        if(node.getFirstExpression() != null)
        {
            node.getFirstExpression().apply(this);
        }
        if(node.getSecondExpression() != null)
        {
            node.getSecondExpression().apply(this);
        }
        outASize2GeometryAdjustment(node);
    }

    public void inAFlipGeometryAdjustment(AFlipGeometryAdjustment node)
    {
        defaultIn(node);
    }

    public void outAFlipGeometryAdjustment(AFlipGeometryAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFlipGeometryAdjustment(AFlipGeometryAdjustment node)
    {
        inAFlipGeometryAdjustment(node);
        if(node.getFlipToken() != null)
        {
            node.getFlipToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAFlipGeometryAdjustment(node);
    }

    public void inASkewGeometryAdjustment(ASkewGeometryAdjustment node)
    {
        defaultIn(node);
    }

    public void outASkewGeometryAdjustment(ASkewGeometryAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASkewGeometryAdjustment(ASkewGeometryAdjustment node)
    {
        inASkewGeometryAdjustment(node);
        if(node.getSkewToken() != null)
        {
            node.getSkewToken().apply(this);
        }
        if(node.getFirstExpression() != null)
        {
            node.getFirstExpression().apply(this);
        }
        if(node.getSecondExpression() != null)
        {
            node.getSecondExpression().apply(this);
        }
        outASkewGeometryAdjustment(node);
    }

    public void inARotateGeometryAdjustment(ARotateGeometryAdjustment node)
    {
        defaultIn(node);
    }

    public void outARotateGeometryAdjustment(ARotateGeometryAdjustment node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARotateGeometryAdjustment(ARotateGeometryAdjustment node)
    {
        inARotateGeometryAdjustment(node);
        if(node.getRotateToken() != null)
        {
            node.getRotateToken().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outARotateGeometryAdjustment(node);
    }

    public void inANumberExpression(ANumberExpression node)
    {
        defaultIn(node);
    }

    public void outANumberExpression(ANumberExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberExpression(ANumberExpression node)
    {
        inANumberExpression(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumberExpression(node);
    }

    public void inANestedExpression(ANestedExpression node)
    {
        defaultIn(node);
    }

    public void outANestedExpression(ANestedExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANestedExpression(ANestedExpression node)
    {
        inANestedExpression(node);
        if(node.getLRbkt() != null)
        {
            node.getLRbkt().apply(this);
        }
        if(node.getExpression2() != null)
        {
            node.getExpression2().apply(this);
        }
        if(node.getRRbkt() != null)
        {
            node.getRRbkt().apply(this);
        }
        outANestedExpression(node);
    }

    public void inAFunctionExpression(AFunctionExpression node)
    {
        defaultIn(node);
    }

    public void outAFunctionExpression(AFunctionExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFunctionExpression(AFunctionExpression node)
    {
        inAFunctionExpression(node);
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        outAFunctionExpression(node);
    }

    public void inANumberExpression2(ANumberExpression2 node)
    {
        defaultIn(node);
    }

    public void outANumberExpression2(ANumberExpression2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumberExpression2(ANumberExpression2 node)
    {
        inANumberExpression2(node);
        if(node.getNumber() != null)
        {
            node.getNumber().apply(this);
        }
        outANumberExpression2(node);
    }

    public void inAFunctionExpression2(AFunctionExpression2 node)
    {
        defaultIn(node);
    }

    public void outAFunctionExpression2(AFunctionExpression2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFunctionExpression2(AFunctionExpression2 node)
    {
        inAFunctionExpression2(node);
        if(node.getFunction() != null)
        {
            node.getFunction().apply(this);
        }
        outAFunctionExpression2(node);
    }

    public void inANestedExpression2(ANestedExpression2 node)
    {
        defaultIn(node);
    }

    public void outANestedExpression2(ANestedExpression2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANestedExpression2(ANestedExpression2 node)
    {
        inANestedExpression2(node);
        if(node.getLRbkt() != null)
        {
            node.getLRbkt().apply(this);
        }
        if(node.getExpression2() != null)
        {
            node.getExpression2().apply(this);
        }
        if(node.getRRbkt() != null)
        {
            node.getRRbkt().apply(this);
        }
        outANestedExpression2(node);
    }

    public void inAComposedExpression2(AComposedExpression2 node)
    {
        defaultIn(node);
    }

    public void outAComposedExpression2(AComposedExpression2 node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComposedExpression2(AComposedExpression2 node)
    {
        inAComposedExpression2(node);
        if(node.getExpression2() != null)
        {
            node.getExpression2().apply(this);
        }
        if(node.getOperator() != null)
        {
            node.getOperator().apply(this);
        }
        if(node.getExpression() != null)
        {
            node.getExpression().apply(this);
        }
        outAComposedExpression2(node);
    }

    public void inAArg0Function(AArg0Function node)
    {
        defaultIn(node);
    }

    public void outAArg0Function(AArg0Function node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArg0Function(AArg0Function node)
    {
        inAArg0Function(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        if(node.getLRbkt() != null)
        {
            node.getLRbkt().apply(this);
        }
        if(node.getRRbkt() != null)
        {
            node.getRRbkt().apply(this);
        }
        outAArg0Function(node);
    }

    public void inAArg1Function(AArg1Function node)
    {
        defaultIn(node);
    }

    public void outAArg1Function(AArg1Function node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArg1Function(AArg1Function node)
    {
        inAArg1Function(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        if(node.getLRbkt() != null)
        {
            node.getLRbkt().apply(this);
        }
        if(node.getFirstExpression() != null)
        {
            node.getFirstExpression().apply(this);
        }
        if(node.getRRbkt() != null)
        {
            node.getRRbkt().apply(this);
        }
        outAArg1Function(node);
    }

    public void inAArg2Function(AArg2Function node)
    {
        defaultIn(node);
    }

    public void outAArg2Function(AArg2Function node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAArg2Function(AArg2Function node)
    {
        inAArg2Function(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        if(node.getLRbkt() != null)
        {
            node.getLRbkt().apply(this);
        }
        if(node.getFirstExpression() != null)
        {
            node.getFirstExpression().apply(this);
        }
        if(node.getComma() != null)
        {
            node.getComma().apply(this);
        }
        if(node.getSecondExpression() != null)
        {
            node.getSecondExpression().apply(this);
        }
        if(node.getRRbkt() != null)
        {
            node.getRRbkt().apply(this);
        }
        outAArg2Function(node);
    }

    public void inAFirstExpression(AFirstExpression node)
    {
        defaultIn(node);
    }

    public void outAFirstExpression(AFirstExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAFirstExpression(AFirstExpression node)
    {
        inAFirstExpression(node);
        if(node.getExpression2() != null)
        {
            node.getExpression2().apply(this);
        }
        outAFirstExpression(node);
    }

    public void inASecondExpression(ASecondExpression node)
    {
        defaultIn(node);
    }

    public void outASecondExpression(ASecondExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASecondExpression(ASecondExpression node)
    {
        inASecondExpression(node);
        if(node.getExpression2() != null)
        {
            node.getExpression2().apply(this);
        }
        outASecondExpression(node);
    }

    public void inAThirdExpression(AThirdExpression node)
    {
        defaultIn(node);
    }

    public void outAThirdExpression(AThirdExpression node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAThirdExpression(AThirdExpression node)
    {
        inAThirdExpression(node);
        if(node.getExpression2() != null)
        {
            node.getExpression2().apply(this);
        }
        outAThirdExpression(node);
    }
}
