/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.lexer;

@SuppressWarnings("serial")
public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
