/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import java.util.*;
import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class ADefaultPathopPathOperation extends PPathopPathOperation
{
    private TPathop _pathop_;
    private TLCbkt _lCbkt_;
    private final LinkedList<PPathPoints> _pathPoints_ = new LinkedList<PPathPoints>();
    private TRCbkt _rCbkt_;

    public ADefaultPathopPathOperation()
    {
        // Constructor
    }

    public ADefaultPathopPathOperation(
        @SuppressWarnings("hiding") TPathop _pathop_,
        @SuppressWarnings("hiding") TLCbkt _lCbkt_,
        @SuppressWarnings("hiding") List<PPathPoints> _pathPoints_,
        @SuppressWarnings("hiding") TRCbkt _rCbkt_)
    {
        // Constructor
        setPathop(_pathop_);

        setLCbkt(_lCbkt_);

        setPathPoints(_pathPoints_);

        setRCbkt(_rCbkt_);

    }

    @Override
    public Object clone()
    {
        return new ADefaultPathopPathOperation(
            cloneNode(this._pathop_),
            cloneNode(this._lCbkt_),
            cloneList(this._pathPoints_),
            cloneNode(this._rCbkt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADefaultPathopPathOperation(this);
    }

    public TPathop getPathop()
    {
        return this._pathop_;
    }

    public void setPathop(TPathop node)
    {
        if(this._pathop_ != null)
        {
            this._pathop_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pathop_ = node;
    }

    public TLCbkt getLCbkt()
    {
        return this._lCbkt_;
    }

    public void setLCbkt(TLCbkt node)
    {
        if(this._lCbkt_ != null)
        {
            this._lCbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lCbkt_ = node;
    }

    public LinkedList<PPathPoints> getPathPoints()
    {
        return this._pathPoints_;
    }

    public void setPathPoints(List<PPathPoints> list)
    {
        this._pathPoints_.clear();
        this._pathPoints_.addAll(list);
        for(PPathPoints e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TRCbkt getRCbkt()
    {
        return this._rCbkt_;
    }

    public void setRCbkt(TRCbkt node)
    {
        if(this._rCbkt_ != null)
        {
            this._rCbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rCbkt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pathop_)
            + toString(this._lCbkt_)
            + toString(this._pathPoints_)
            + toString(this._rCbkt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pathop_ == child)
        {
            this._pathop_ = null;
            return;
        }

        if(this._lCbkt_ == child)
        {
            this._lCbkt_ = null;
            return;
        }

        if(this._pathPoints_.remove(child))
        {
            return;
        }

        if(this._rCbkt_ == child)
        {
            this._rCbkt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pathop_ == oldChild)
        {
            setPathop((TPathop) newChild);
            return;
        }

        if(this._lCbkt_ == oldChild)
        {
            setLCbkt((TLCbkt) newChild);
            return;
        }

        for(ListIterator<PPathPoints> i = this._pathPoints_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPathPoints) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rCbkt_ == oldChild)
        {
            setRCbkt((TRCbkt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
