/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class AListLoopShapeReplacementBody extends PLoopShapeReplacementBody
{
    private PListShapeReplacement _listShapeReplacement_;

    public AListLoopShapeReplacementBody()
    {
        // Constructor
    }

    public AListLoopShapeReplacementBody(
        @SuppressWarnings("hiding") PListShapeReplacement _listShapeReplacement_)
    {
        // Constructor
        setListShapeReplacement(_listShapeReplacement_);

    }

    @Override
    public Object clone()
    {
        return new AListLoopShapeReplacementBody(
            cloneNode(this._listShapeReplacement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListLoopShapeReplacementBody(this);
    }

    public PListShapeReplacement getListShapeReplacement()
    {
        return this._listShapeReplacement_;
    }

    public void setListShapeReplacement(PListShapeReplacement node)
    {
        if(this._listShapeReplacement_ != null)
        {
            this._listShapeReplacement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listShapeReplacement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listShapeReplacement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listShapeReplacement_ == child)
        {
            this._listShapeReplacement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listShapeReplacement_ == oldChild)
        {
            setListShapeReplacement((PListShapeReplacement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
