/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class AListMultiPathOperationBody extends PMultiPathOperationBody
{
    private PListPathOperation _listPathOperation_;

    public AListMultiPathOperationBody()
    {
        // Constructor
    }

    public AListMultiPathOperationBody(
        @SuppressWarnings("hiding") PListPathOperation _listPathOperation_)
    {
        // Constructor
        setListPathOperation(_listPathOperation_);

    }

    @Override
    public Object clone()
    {
        return new AListMultiPathOperationBody(
            cloneNode(this._listPathOperation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListMultiPathOperationBody(this);
    }

    public PListPathOperation getListPathOperation()
    {
        return this._listPathOperation_;
    }

    public void setListPathOperation(PListPathOperation node)
    {
        if(this._listPathOperation_ != null)
        {
            this._listPathOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listPathOperation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._listPathOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._listPathOperation_ == child)
        {
            this._listPathOperation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._listPathOperation_ == oldChild)
        {
            setListPathOperation((PListPathOperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
