/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class ALoopPathOperationDeclaration extends PPathOperationDeclaration
{
    private PLoopPathOperation _loopPathOperation_;

    public ALoopPathOperationDeclaration()
    {
        // Constructor
    }

    public ALoopPathOperationDeclaration(
        @SuppressWarnings("hiding") PLoopPathOperation _loopPathOperation_)
    {
        // Constructor
        setLoopPathOperation(_loopPathOperation_);

    }

    @Override
    public Object clone()
    {
        return new ALoopPathOperationDeclaration(
            cloneNode(this._loopPathOperation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALoopPathOperationDeclaration(this);
    }

    public PLoopPathOperation getLoopPathOperation()
    {
        return this._loopPathOperation_;
    }

    public void setLoopPathOperation(PLoopPathOperation node)
    {
        if(this._loopPathOperation_ != null)
        {
            this._loopPathOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._loopPathOperation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._loopPathOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._loopPathOperation_ == child)
        {
            this._loopPathOperation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._loopPathOperation_ == oldChild)
        {
            setLoopPathOperation((PLoopPathOperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
