/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import java.util.*;
import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class ALoopPathOperation extends PLoopPathOperation
{
    private TNumber _number_;
    private TStar _star_;
    private TLCbkt _lCbkt_;
    private final LinkedList<PPathAdjustment> _pathAdjustment_ = new LinkedList<PPathAdjustment>();
    private TRCbkt _rCbkt_;
    private PLoopPathOperationBody _loopPathOperationBody_;

    public ALoopPathOperation()
    {
        // Constructor
    }

    public ALoopPathOperation(
        @SuppressWarnings("hiding") TNumber _number_,
        @SuppressWarnings("hiding") TStar _star_,
        @SuppressWarnings("hiding") TLCbkt _lCbkt_,
        @SuppressWarnings("hiding") List<PPathAdjustment> _pathAdjustment_,
        @SuppressWarnings("hiding") TRCbkt _rCbkt_,
        @SuppressWarnings("hiding") PLoopPathOperationBody _loopPathOperationBody_)
    {
        // Constructor
        setNumber(_number_);

        setStar(_star_);

        setLCbkt(_lCbkt_);

        setPathAdjustment(_pathAdjustment_);

        setRCbkt(_rCbkt_);

        setLoopPathOperationBody(_loopPathOperationBody_);

    }

    @Override
    public Object clone()
    {
        return new ALoopPathOperation(
            cloneNode(this._number_),
            cloneNode(this._star_),
            cloneNode(this._lCbkt_),
            cloneList(this._pathAdjustment_),
            cloneNode(this._rCbkt_),
            cloneNode(this._loopPathOperationBody_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALoopPathOperation(this);
    }

    public TNumber getNumber()
    {
        return this._number_;
    }

    public void setNumber(TNumber node)
    {
        if(this._number_ != null)
        {
            this._number_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._number_ = node;
    }

    public TStar getStar()
    {
        return this._star_;
    }

    public void setStar(TStar node)
    {
        if(this._star_ != null)
        {
            this._star_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._star_ = node;
    }

    public TLCbkt getLCbkt()
    {
        return this._lCbkt_;
    }

    public void setLCbkt(TLCbkt node)
    {
        if(this._lCbkt_ != null)
        {
            this._lCbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lCbkt_ = node;
    }

    public LinkedList<PPathAdjustment> getPathAdjustment()
    {
        return this._pathAdjustment_;
    }

    public void setPathAdjustment(List<PPathAdjustment> list)
    {
        this._pathAdjustment_.clear();
        this._pathAdjustment_.addAll(list);
        for(PPathAdjustment e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TRCbkt getRCbkt()
    {
        return this._rCbkt_;
    }

    public void setRCbkt(TRCbkt node)
    {
        if(this._rCbkt_ != null)
        {
            this._rCbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rCbkt_ = node;
    }

    public PLoopPathOperationBody getLoopPathOperationBody()
    {
        return this._loopPathOperationBody_;
    }

    public void setLoopPathOperationBody(PLoopPathOperationBody node)
    {
        if(this._loopPathOperationBody_ != null)
        {
            this._loopPathOperationBody_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._loopPathOperationBody_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._number_)
            + toString(this._star_)
            + toString(this._lCbkt_)
            + toString(this._pathAdjustment_)
            + toString(this._rCbkt_)
            + toString(this._loopPathOperationBody_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._number_ == child)
        {
            this._number_ = null;
            return;
        }

        if(this._star_ == child)
        {
            this._star_ = null;
            return;
        }

        if(this._lCbkt_ == child)
        {
            this._lCbkt_ = null;
            return;
        }

        if(this._pathAdjustment_.remove(child))
        {
            return;
        }

        if(this._rCbkt_ == child)
        {
            this._rCbkt_ = null;
            return;
        }

        if(this._loopPathOperationBody_ == child)
        {
            this._loopPathOperationBody_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._number_ == oldChild)
        {
            setNumber((TNumber) newChild);
            return;
        }

        if(this._star_ == oldChild)
        {
            setStar((TStar) newChild);
            return;
        }

        if(this._lCbkt_ == oldChild)
        {
            setLCbkt((TLCbkt) newChild);
            return;
        }

        for(ListIterator<PPathAdjustment> i = this._pathAdjustment_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPathAdjustment) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rCbkt_ == oldChild)
        {
            setRCbkt((TRCbkt) newChild);
            return;
        }

        if(this._loopPathOperationBody_ == oldChild)
        {
            setLoopPathOperationBody((PLoopPathOperationBody) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
