/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class AMultiShapeReplacementDeclaration extends PShapeReplacementDeclaration
{
    private PMultiShapeReplacement _multiShapeReplacement_;

    public AMultiShapeReplacementDeclaration()
    {
        // Constructor
    }

    public AMultiShapeReplacementDeclaration(
        @SuppressWarnings("hiding") PMultiShapeReplacement _multiShapeReplacement_)
    {
        // Constructor
        setMultiShapeReplacement(_multiShapeReplacement_);

    }

    @Override
    public Object clone()
    {
        return new AMultiShapeReplacementDeclaration(
            cloneNode(this._multiShapeReplacement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiShapeReplacementDeclaration(this);
    }

    public PMultiShapeReplacement getMultiShapeReplacement()
    {
        return this._multiShapeReplacement_;
    }

    public void setMultiShapeReplacement(PMultiShapeReplacement node)
    {
        if(this._multiShapeReplacement_ != null)
        {
            this._multiShapeReplacement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multiShapeReplacement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multiShapeReplacement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multiShapeReplacement_ == child)
        {
            this._multiShapeReplacement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multiShapeReplacement_ == oldChild)
        {
            setMultiShapeReplacement((PMultiShapeReplacement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
