/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import java.util.*;
import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class AOrderedPathCommand extends PPathCommand
{
    private TPathcmd _pathcmd_;
    private TLSbkt _lSbkt_;
    private final LinkedList<PPathAdjustment> _pathAdjustment_ = new LinkedList<PPathAdjustment>();
    private TRSbkt _rSbkt_;

    public AOrderedPathCommand()
    {
        // Constructor
    }

    public AOrderedPathCommand(
        @SuppressWarnings("hiding") TPathcmd _pathcmd_,
        @SuppressWarnings("hiding") TLSbkt _lSbkt_,
        @SuppressWarnings("hiding") List<PPathAdjustment> _pathAdjustment_,
        @SuppressWarnings("hiding") TRSbkt _rSbkt_)
    {
        // Constructor
        setPathcmd(_pathcmd_);

        setLSbkt(_lSbkt_);

        setPathAdjustment(_pathAdjustment_);

        setRSbkt(_rSbkt_);

    }

    @Override
    public Object clone()
    {
        return new AOrderedPathCommand(
            cloneNode(this._pathcmd_),
            cloneNode(this._lSbkt_),
            cloneList(this._pathAdjustment_),
            cloneNode(this._rSbkt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrderedPathCommand(this);
    }

    public TPathcmd getPathcmd()
    {
        return this._pathcmd_;
    }

    public void setPathcmd(TPathcmd node)
    {
        if(this._pathcmd_ != null)
        {
            this._pathcmd_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pathcmd_ = node;
    }

    public TLSbkt getLSbkt()
    {
        return this._lSbkt_;
    }

    public void setLSbkt(TLSbkt node)
    {
        if(this._lSbkt_ != null)
        {
            this._lSbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lSbkt_ = node;
    }

    public LinkedList<PPathAdjustment> getPathAdjustment()
    {
        return this._pathAdjustment_;
    }

    public void setPathAdjustment(List<PPathAdjustment> list)
    {
        this._pathAdjustment_.clear();
        this._pathAdjustment_.addAll(list);
        for(PPathAdjustment e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TRSbkt getRSbkt()
    {
        return this._rSbkt_;
    }

    public void setRSbkt(TRSbkt node)
    {
        if(this._rSbkt_ != null)
        {
            this._rSbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rSbkt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pathcmd_)
            + toString(this._lSbkt_)
            + toString(this._pathAdjustment_)
            + toString(this._rSbkt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pathcmd_ == child)
        {
            this._pathcmd_ = null;
            return;
        }

        if(this._lSbkt_ == child)
        {
            this._lSbkt_ = null;
            return;
        }

        if(this._pathAdjustment_.remove(child))
        {
            return;
        }

        if(this._rSbkt_ == child)
        {
            this._rSbkt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pathcmd_ == oldChild)
        {
            setPathcmd((TPathcmd) newChild);
            return;
        }

        if(this._lSbkt_ == oldChild)
        {
            setLSbkt((TLSbkt) newChild);
            return;
        }

        for(ListIterator<PPathAdjustment> i = this._pathAdjustment_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPathAdjustment) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rSbkt_ == oldChild)
        {
            setRSbkt((TRSbkt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
