/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import java.util.*;
import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class AOrderedTileDeclaration extends PTileDeclaration
{
    private TTile _tile_;
    private TLSbkt _lSbkt_;
    private final LinkedList<PTileAdjustment> _tileAdjustment_ = new LinkedList<PTileAdjustment>();
    private TRSbkt _rSbkt_;

    public AOrderedTileDeclaration()
    {
        // Constructor
    }

    public AOrderedTileDeclaration(
        @SuppressWarnings("hiding") TTile _tile_,
        @SuppressWarnings("hiding") TLSbkt _lSbkt_,
        @SuppressWarnings("hiding") List<PTileAdjustment> _tileAdjustment_,
        @SuppressWarnings("hiding") TRSbkt _rSbkt_)
    {
        // Constructor
        setTile(_tile_);

        setLSbkt(_lSbkt_);

        setTileAdjustment(_tileAdjustment_);

        setRSbkt(_rSbkt_);

    }

    @Override
    public Object clone()
    {
        return new AOrderedTileDeclaration(
            cloneNode(this._tile_),
            cloneNode(this._lSbkt_),
            cloneList(this._tileAdjustment_),
            cloneNode(this._rSbkt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOrderedTileDeclaration(this);
    }

    public TTile getTile()
    {
        return this._tile_;
    }

    public void setTile(TTile node)
    {
        if(this._tile_ != null)
        {
            this._tile_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tile_ = node;
    }

    public TLSbkt getLSbkt()
    {
        return this._lSbkt_;
    }

    public void setLSbkt(TLSbkt node)
    {
        if(this._lSbkt_ != null)
        {
            this._lSbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lSbkt_ = node;
    }

    public LinkedList<PTileAdjustment> getTileAdjustment()
    {
        return this._tileAdjustment_;
    }

    public void setTileAdjustment(List<PTileAdjustment> list)
    {
        this._tileAdjustment_.clear();
        this._tileAdjustment_.addAll(list);
        for(PTileAdjustment e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TRSbkt getRSbkt()
    {
        return this._rSbkt_;
    }

    public void setRSbkt(TRSbkt node)
    {
        if(this._rSbkt_ != null)
        {
            this._rSbkt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rSbkt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tile_)
            + toString(this._lSbkt_)
            + toString(this._tileAdjustment_)
            + toString(this._rSbkt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tile_ == child)
        {
            this._tile_ = null;
            return;
        }

        if(this._lSbkt_ == child)
        {
            this._lSbkt_ = null;
            return;
        }

        if(this._tileAdjustment_.remove(child))
        {
            return;
        }

        if(this._rSbkt_ == child)
        {
            this._rSbkt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tile_ == oldChild)
        {
            setTile((TTile) newChild);
            return;
        }

        if(this._lSbkt_ == oldChild)
        {
            setLSbkt((TLSbkt) newChild);
            return;
        }

        for(ListIterator<PTileAdjustment> i = this._tileAdjustment_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PTileAdjustment) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._rSbkt_ == oldChild)
        {
            setRSbkt((TRSbkt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
