/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class APathopPathOperation extends PPathOperation
{
    private PPathopPathOperation _pathopPathOperation_;

    public APathopPathOperation()
    {
        // Constructor
    }

    public APathopPathOperation(
        @SuppressWarnings("hiding") PPathopPathOperation _pathopPathOperation_)
    {
        // Constructor
        setPathopPathOperation(_pathopPathOperation_);

    }

    @Override
    public Object clone()
    {
        return new APathopPathOperation(
            cloneNode(this._pathopPathOperation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPathopPathOperation(this);
    }

    public PPathopPathOperation getPathopPathOperation()
    {
        return this._pathopPathOperation_;
    }

    public void setPathopPathOperation(PPathopPathOperation node)
    {
        if(this._pathopPathOperation_ != null)
        {
            this._pathopPathOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pathopPathOperation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pathopPathOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pathopPathOperation_ == child)
        {
            this._pathopPathOperation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pathopPathOperation_ == oldChild)
        {
            setPathopPathOperation((PPathopPathOperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
