/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class ASimplePathOperation extends PPathOperation
{
    private PSimplePathOperation _simplePathOperation_;

    public ASimplePathOperation()
    {
        // Constructor
    }

    public ASimplePathOperation(
        @SuppressWarnings("hiding") PSimplePathOperation _simplePathOperation_)
    {
        // Constructor
        setSimplePathOperation(_simplePathOperation_);

    }

    @Override
    public Object clone()
    {
        return new ASimplePathOperation(
            cloneNode(this._simplePathOperation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimplePathOperation(this);
    }

    public PSimplePathOperation getSimplePathOperation()
    {
        return this._simplePathOperation_;
    }

    public void setSimplePathOperation(PSimplePathOperation node)
    {
        if(this._simplePathOperation_ != null)
        {
            this._simplePathOperation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._simplePathOperation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._simplePathOperation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._simplePathOperation_ == child)
        {
            this._simplePathOperation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._simplePathOperation_ == oldChild)
        {
            setSimplePathOperation((PSimplePathOperation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
