/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class ASizePathAdjustment extends PPathAdjustment
{
    private TSizeToken _sizeToken_;
    private PExpression _expression_;

    public ASizePathAdjustment()
    {
        // Constructor
    }

    public ASizePathAdjustment(
        @SuppressWarnings("hiding") TSizeToken _sizeToken_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setSizeToken(_sizeToken_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new ASizePathAdjustment(
            cloneNode(this._sizeToken_),
            cloneNode(this._expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASizePathAdjustment(this);
    }

    public TSizeToken getSizeToken()
    {
        return this._sizeToken_;
    }

    public void setSizeToken(TSizeToken node)
    {
        if(this._sizeToken_ != null)
        {
            this._sizeToken_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._sizeToken_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._sizeToken_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._sizeToken_ == child)
        {
            this._sizeToken_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._sizeToken_ == oldChild)
        {
            setSizeToken((TSizeToken) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
