/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.*;

@SuppressWarnings("nls")
public final class AX1PathPoints extends PPathPoints
{
    private TX1Token _x1Token_;
    private PExpression _expression_;

    public AX1PathPoints()
    {
        // Constructor
    }

    public AX1PathPoints(
        @SuppressWarnings("hiding") TX1Token _x1Token_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setX1Token(_x1Token_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AX1PathPoints(
            cloneNode(this._x1Token_),
            cloneNode(this._expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAX1PathPoints(this);
    }

    public TX1Token getX1Token()
    {
        return this._x1Token_;
    }

    public void setX1Token(TX1Token node)
    {
        if(this._x1Token_ != null)
        {
            this._x1Token_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._x1Token_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._x1Token_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._x1Token_ == child)
        {
            this._x1Token_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._x1Token_ == oldChild)
        {
            setX1Token((TX1Token) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
