/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

public abstract class PShapeReplacementDeclaration extends Node
{
    // Empty body
}
