/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.Analysis;

@SuppressWarnings("nls")
public final class TY1Token extends Token
{
    public TY1Token()
    {
        super.setText("y1");
    }

    public TY1Token(int line, int pos)
    {
        super.setText("y1");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TY1Token(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTY1Token(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TY1Token text.");
    }
}
