/* This file was generated by SableCC (http://www.sablecc.org/). */

package net.sf.jame.contextfree.cfdg.node;

import net.sf.jame.contextfree.cfdg.analysis.Analysis;

@SuppressWarnings("nls")
public final class TZToken extends Token
{
    public TZToken()
    {
        super.setText("z");
    }

    public TZToken(int line, int pos)
    {
        super.setText("z");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TZToken(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTZToken(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TZToken text.");
    }
}
